<main class="main-wrapper clearfix">
<!-- Page Title Area -->
<div class="row page-title clearfix">

    <!-- /.page-title-right -->
    <div class="page-title-left">
        <h5 class="mr-0 mr-r-5"><?= $this->translate("Master Item") ?></h5>
    </div>
    <!-- /.page-title-right -->

</div>
<!-- /.page-title -->

<!-- =================================== -->
<!-- Different data widgets ============ -->
<!-- =================================== -->
<div class="widget-list">
    <div class="row">
        <div class="col-md-12 widget-holder">
            <div class="widget-bg">
                <div class="widget-heading clearfix">
                    <h5><?= $this->translate("Master Item Data") ?></h5>
                    <br><br>
                    <a href="javascript:void(0);" class="btn btn-primary dropdown-toggle ripple" data-toggle="dropdown">
                        <i class="material-icons list-icon fs-24">playlist_add</i> <?= $this->translate("Add New") ?>
                    </a>
                </div>
                
                <!-- /.widget-heading -->
                <div class="widget-body clearfix">
                    <table id="masterunit" class="table table-striped table-responsive">
                        <thead>
                            <tr>
                                <th><?= $this->translate("Name") ?></th>
                                <th><?= $this->translate("Unit") ?></th>
                                <th><?= $this->translate("Registration Number") ?></th>
                                <th><?= $this->translate("Action") ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <!-- /.widget-body -->
            </div>
            <!-- /.widget-bg -->
        </div>
        <!-- /.widget-holder -->
    </div>
    <!-- /.row -->
</div>
<!-- /.widget-list -->

</main>
<!-- /.main-wrappper -->

<?php
$masterunit = $this->url('masterunit',["action" => "ajax"]);

//inline script
$this->inlineScript()->captureStart();
echo <<<JS
var masterunit;
masterunit = "$masterunit";
$( document ).ready(function() {
//load table
table = $('#masterunit').DataTable({
      processing: true,
      serverSide: true,
      searching: true,
      ajax: {
                url: masterunit,
                type: "GET",
                columnDefs: [ { targets: -1, orderable: false } ]
           }
 });
});
JS;
$this->inlineScript()->captureEnd();