<div id="wrapper" class="row wrapper">
<div class="col-10 ml-sm-auto col-sm-6 col-md-4 ml-md-auto login-center mx-auto">
    <div class="navbar-header text-center">
        <a href="index.html">
            <img alt="" src="<?= $this->basePath("template1") ?>/demo/logo-expand-dark.png">
        </a>
    </div>
    <!-- /.navbar-header -->
    <form class="form-material" method="post">
        
        <div class="form-group">
            <input type="text" placeholder="username" class="form-control form-control-line" name="username" id="username">
            <label for="example-email">Username</label>
        </div>
        
        <div class="form-group">
            <input type="password" placeholder="password" class="form-control form-control-line" name="password">
            <label>Password</label>
        </div>

        <div class="form-group">
            <button class="btn btn-block btn-lg btn-color-scheme ripple" type="submit">Login</button>
        </div>

        <?php if(isset($message[0])): ?>
        <div class="form-group">
            <p class="text-danger text-center"><?= $message[0] ?></p>
        </div>
        <?php endif; ?>
        <!-- /.form-group -->

    </form>
    <!-- /.form-material -->
</div>
<!-- /.login-center -->
</div>
<!-- /.body-container -->