<!-- ==========================
     CONTENT
=========================== -->
<main class="login">

     <!-- Title -->
     <h1 class="login__title">Start blazing</h1>

     <!-- Form -->
     <form class="login__form" id="login-form" action="<?= $this->url('login') ?>" method="post">

          <!-- Email -->
          <input class="login__input" id="login-form-email" name="email" type="email" placeholder="Email" aria-label="Enter your email">
          <!-- Password -->
          <input class="login__input" id="login-form-password" name="password" type="password" placeholder="Password" aria-label="Enter your password">
          <!-- Submit -->
          <input type="submit" class="login__submit" value="Log in"/>
          <!-- Forget -->
          <div class="login__forget">
               <a href="<?= $this->url('forgetpass') ?>">Forget your password?</a>
          </div>
          <input name="redirect" type="hidden" value="<?php echo $data['redirect'] ?>"/>
     </form>

     <?php if($loginErr): ?>
     <!-- Notification -->
     <div class="notification notification--narrow">
          <div class="notification__msg notification__msg--error">
               <p><?= $messageErr[0] ?></p>
          </div>
     </div>
     <?php endif; ?>
</main>
