<!-- ==========================
     CONTENT
=========================== -->
<main class="sign-up-2">

     <!-- Title -->
     <h1 class="sign-up-2__title">Account activation success</h1>

     <!-- Description -->
     <div class="sign-up-2__desc">
          <p>Your account activated.</p>
          <p>Please login with link below.</p>
     </div>

     <!-- Resend link -->
     <div class="sign-up-2__resend">
          <a href="<?= $this->url("login") ?>">Login</a>
     </div>

</main>
