<!-- ==========================
     CONTENT
=========================== -->
<main class="sign-up-2">

     <!-- Title -->
     <h1 class="sign-up-2__title">Activate your account</h1>

     <!-- Description -->
     <div class="sign-up-2__desc">
          <p>An email have sent to <strong>"<?= $email ?>"</strong>.</p>
          <p>Please follow the instructions in the email to reset your password.</p>
     </div>

     <!-- Subtitle -->
     <p class="sign-up-2__subtitle">Did not receive the email?</p>

     <!-- Resend link -->
     <div class="sign-up-2__resend">
          <a href="<?= $this->url("resend",["token" => $token]) ?>">Resend confirmation email</a>
     </div>

</main>
