<!-- ==========================
     CONTENT
=========================== -->
<main class="sign-up-1">
     <h1 class="sign-up-1__title">Create an account</h1>
     <form class="sign-up-1__form" id="sign-up-form" action="<?= $this->url('signup') ?>" method="post">
          <input class="sign-up-1__input" id="sign-up-form-email" name="email" type="email" placeholder="Email" aria-label="Enter your email">
          <input class="sign-up-1__input" id="sign-up-form-password" name="password" type="password" placeholder="Password" aria-label="Enter your password">

          <!-- Password Tip -->
          <p class="sign-up-1__pass-tip">Password must be at least 8 characters in length and contain letters, upper letter, numbers, and special characters.</p>

          <!-- Captcha -->
          <div class="sign-up-1__captcha">
               <div class="g-recaptcha" data-sitekey="6Lfr8DEUAAAAAPgK7K2SxM8nr0fMdbUBaqKivA2z"></div>
          </div>

          <p class="sign-up-1__terms">By signing up you agree to our <a href="<?= $this->url('login') ?>">Terms of Use</a> and <a href="#">Privacy Policy.</a></p>
          <button class="sign-up-1__submit">Sign up</button>

          <!-- Login -->
          <div class="sign-up-1__login-link">
               <a href="<?= $this->url('login') ?>">Already signed up? Login here</a>
          </div>

     </form>

     <?php if(!empty($message)): ?>
     <!-- Notification -->
     <div class="notification notification--narrow">
          <div class="notification__msg notification__msg--error">
               <p><?= $message ?></p>
          </div>
     </div>
     <?php endif; ?>

</main>

<?php
$this->inlineScript()->prependFile("https://www.google.com/recaptcha/api.js")
?>
