<!-- ==========================
     CONTENT
=========================== -->
<main class="forget-1">

     <!-- Title -->
     <h1 class="forget-1__title">Forget password</h1>

     <!-- Description -->
     <p class="forget-1__desc">Enter your email address and we’ll send a link that will let you reset your password.</p>

     <!-- Form -->
     <form class="forget-1__form" id="forget-form" action="<?= $this->url('forgetpass') ?>" method="post">

          <!-- Email -->
          <input class="forget-1__input" id="forget-form-email" name="email" type="email" placeholder="Email" aria-label="Enter your email">

          <!-- Captcha -->
          <div class="sign-up-1__captcha">
               <div class="g-recaptcha" data-sitekey="6Lfr8DEUAAAAAPgK7K2SxM8nr0fMdbUBaqKivA2z"></div>
          </div>

          <!-- Submit -->
          <button class="forget-1__submit">Reset password</button>

     </form>

     <?php if(!empty($message)): ?>
     <!-- Notification -->
     <div class="notification notification--narrow">
          <div class="notification__msg notification__msg--error">
               <p><?= $message ?></p>
          </div>
     </div>
     <?php endif; ?>

</main>

<?php
$this->inlineScript()->prependFile("https://www.google.com/recaptcha/api.js")
?>
