<!-- ==========================
     CONTENT
=========================== -->
<main class="forget-2">

     <!-- Title -->
     <h1 class="forget-2__title">Email sent</h1>

     <!-- Description -->
     <div class="forget-2__desc">
          <p>An email have sent to <strong>"<?= $email ?>"</strong>.</p>
          <p>Please follow the instructions in the email to reset your password.</p>
     </div>

     <!-- Resent -->
     <div class="forget-2__resent">
          <a href="<?= $this->url('forgetpass',['action' => 'resend'])."?token=".$token ?>&email=<?= $email ?>" >Resent email</a>
     </div>

     <?php if(!empty($message)): ?>
     <!-- Notification -->
     <div class="notification notification--narrow">
          <div class="notification__msg notification__msg--error">
               <p><?= $message ?></p>
          </div>
     </div>
     <?php endif; ?>

</main>
